### PR TITLE
New GPU Info class

### PR DESCRIPTION
**Pull request by CodePhase**
This class will make it easier to get information from a user's GPU.  Currently it only works with NVIDIA cards but support for ATI and Intel is planned.

### CODE REVIEW

**Comment by CodePhase** [comment]
@kmkolasinski, you're quick!  I just now noticed the comments you made on my previous (and now deleted) pull request about just comparing the vendor string instead of using the enum.  It might be a good idea so let me have a look at that.

**Comment by CodePhase** [comment]
I reviewed the vendor query code and remembered why I had to use an enum.  The switch/case statements in the available and total memory functions need the enum because they can't compare strings.  Otherwise I'd have to use a bunch of if statements, which I don't prefer.  Still, I'm open to suggestions so if you have an idea let me know!

**Comment by CodePhase** [comment]
One thing I don't like about how I did this is that all of the details are re-queried at every replot.  Getting the card vendor and total memory probably only have to be done one time.

**Comment by kmkolasinski** [comment]
This can be solved with static variables defined in class you wrote or just like here: [one time](https://github.com/kmkolasinski/AwesomeBump/blob/master/Sources/mainwindow.cpp#L1055)

**Comment by CodePhase** [comment]
Hmm, interesting.  I'll definitely check this out; it seems promising.

**Pull request merged**
