### PR TITLE
Cleanup, models update, add models to selector & better structure of folders

### PR DESCRIPTION
**Pull request by Hevedy**
- Old models files removed.
- Added new models.
- Added new models to selector in app.
- Moved folders, for better struct.
- Fix windows compiler errors with Utils struct:

-#include "qopenglerrorcheck.h"
-#include "utils/tinyobj/tiny_obj_loader.h"
to
+#include "../qopenglerrorcheck.h"
+#include "tinyobj/tiny_obj_loader.h"

### CODE REVIEW

**Comment by kmkolasinski** [comment]
Hi, thanks a lot. I like it!
I will take a look on this pull next week. I'm busy now. 

PS: Thanks for solving the MikeM2 problem, I was out of the internet yesterday. 
Best

**Comment by Hevedy** [comment]
Okay thanks you :)

**Comment by kmkolasinski** [comment]
Hi, I managed to merge your changes, but I cannot force GitHub to update the pull request this time :/
So, I have two questions:
1) Do you know how to make it?
2) Can you try current version of AB? I added some initial PBR functionalities, just need someone to test it.

**Comment by Hevedy** [comment]
Wow your merged manually ? nice.
Yes looks like this PR have issues, this display me a message: (This pull request contains merge conflicts that must be resolved.) Probably is a problem at update my fork with your same changed ? no idea or at move in a pull the .gitignore.
Anyway you have added that, no ? then close this, next time i need manage this better :)
I going to check that changes.
Thanks you.

**Comment by kmkolasinski** [comment]
I used git mergetool command to merge your PR, but I had to do many things manualy. because I have already changed some parts of code. I have no idea how to force GitHub to confirm the merged files.  
Ok, then I'm closing this PR. 
There is no license file for your models?

**Comment by Hevedy** [comment]
Is there https://github.com/kmkolasinski/AwesomeBump/blob/master/Bin/Core/3D/Licence.txt is with the models :)
*Change in the file https://github.com/kmkolasinski/AwesomeBump/blob/master/Sources/utils/qglbuffers.cpp
the include from #include "utils/qglbuffers.h" to #include "qglbuffers.h"
Nice changes, nice skyboxes and light :+1:

**Comment by kmkolasinski** [comment]
Ok, glad it works fine :) 
I work on 3.0 version.  

PS: Ah, I didn't notice the license file! Thanks :)

**Comment by Hevedy** [comment]
Wow nice, if in the 3.0 is the PBR will be awesome.

**Pull request closed without merging**
