### PR TITLE
New GPU Info Class

### PR DESCRIPTION
**Pull request by CodePhase**
This new class will allow for easier and more efficient information gathering from a user's GPU.  Right now it only supports NVIDIA cards but ATI and Intel support are planned.

### CODE REVIEW

**Comment by CodePhase** [comment]
Pull request isn't playing nice with my branch rebases and wants to change too many files.  I'll create a new one that is more appropriate.

**Comment by kmkolasinski** [comment]
Yeah thats always happen when more than one person work on the same code.

**Comment by ppiecuch** [comment]
Hi - OSX doesn't have these extensions available so would be good to not to
show that status on Mac (it is always 0) There are some workarounds to get
GPU mem usage but not with opengl extensions.(
http://stackoverflow.com/questions/10110658/programmatically-get-gpu-percent-usage-in-os-x)
I will also try to include that feature later.

Regards
P.

On Sun, Nov 15, 2015 at 3:43 PM, CodePhase <notifications@github.com> wrote:

> This new class will allow for easier and more efficient information
> gathering from a user's GPU. Right now it only supports NVIDIA cards but
> ATI and Intel support are planned.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/kmkolasinski/AwesomeBump/pull/59
> Commit Summary
>
>    - Adding new class to cmake compile list and dropping useless command
>    as indicated in commit 22d041dc00be2542bc9a4e018728599d059391f2.
>    - Created new GpuInfo class to get information about the user's
>    graphics card. Only NVIDIA cards are supported at this time.
>    - Another proposal for the 3D settings widget.
>
> File Changes
>
>    - *M* CMakeLists.txt
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-0> (9)
>    - *M* Sources/dockwidget3dsettings.cpp
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-1> (7)
>    - *M* Sources/dockwidget3dsettings.h
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-2> (2)
>    - *M* Sources/dockwidget3dsettings.ui
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-3>
>    (2127)
>    - *M* Sources/glimageeditor.cpp
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-4> (1)
>    - *M* Sources/glwidget.cpp
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-5> (2)
>    - *A* Sources/gpuinfo.cpp
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-6>
>    (139)
>    - *A* Sources/gpuinfo.h
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-7>
>    (58)
>    - *M* Sources/mainwindow.cpp
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-8>
>    (80)
>    - *M* Sources/mainwindow.h
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-9> (1)
>    - *M* Sources/mainwindow.ui
>    <https://github.com/kmkolasinski/AwesomeBump/pull/59/files#diff-10>
>    (41)
>
> Patch Links:
>
>    - https://github.com/kmkolasinski/AwesomeBump/pull/59.patch
>    - https://github.com/kmkolasinski/AwesomeBump/pull/59.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmkolasinski/AwesomeBump/pull/59>.
>



-- 
More:
 >> (http://komsoft.ath.cx/ <http://komsoft.ath.cx/spider.html>)
 >> (http://pawelp.ath.cx/ <http://komsoft.ath.cx/spider.html>)

**Comment by CodePhase** [comment]
Ok, thanks for the feedback.  I'll put in that workaround and see if there's something that can be done later to implement a proper fix for this.

**Comment by CodePhase** [comment]
Addressed in #63.  If you could test it I'd be grateful.

**Pull request closed without merging**
